# Site settings
title: MayDay.US
email: info@mayone.us
description: "MayDay.US - SuperPAC to end all SuperPACs. Join our effort to win a Congress committed to reforming the influence of money in Politics."
baseurl:

# Build settings
markdown: kramdown
permalink: pretty
